language: python
python:
  - "2.7"

env:
  - DJANGO=1.3.1
  - DJANGO=1.4

# Starting xvfb (X Virtual Framebuffer)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r badges/requirements.txt --use-mirrors

# command to run tests, e.g. python setup.py test
script:  python badges/manage.py test badge
                                      dashboard
                                      notifications
                                      oauthclient
                                      open_badges
                                      p2pu_user
                                      project
 --settings=badges.settings

notifications:
  email:
    on_success: change
    on_failure: change
